source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.1'
use_frameworks!

target 'NetworkKit_Example' do
  pod 'NetworkKit', :path => '../'

  target 'NetworkKit_Tests' do
    inherit! :search_paths

    
  end
end
